parameters:
    enuygun_com_dfp.control_code_listener.class: EnuygunCom\DfpBundle\EventListener\ControlCodeListener
    enuygun_com_dfp.collection.class: EnuygunCom\DfpBundle\Model\Collection
    enuygun_com_dfp.settings.class: EnuygunCom\DfpBundle\Model\Settings
    enuygun_com_dfp.twig.extension.class: EnuygunCom\DfpBundle\Twig\Extension\DfpExtension

    enuygun_com_dfp.publisher_id: ~
    enuygun_com_dfp.default_div_class: ~
    enuygun_com_dfp.targets: [ ]
    enuygun_com_dfp.cache_lifetime: 300
    enuygun_com_dfp.dbal_connection: @doctrine.dbal.default_connection
    enuygun_com_dfp.memcached: @memcached_client

services:
    enuygun_com_dfp.collection:
        class: %enuygun_com_dfp.collection.class%

    enuygun_com_dfp.settings:
        class: %enuygun_com_dfp.settings.class%
        arguments: [%enuygun_com_dfp.publisher_id%, %enuygun_com_dfp.default_div_class%, %enuygun_com_dfp.targets%, %enuygun_com_dfp.cache_lifetime%, @kernel, %enuygun_com_dfp.dbal_connection%, %enuygun_com_dfp.memcached%]

    enuygun_com_dfp.control_code_listener:
        class: %enuygun_com_dfp.control_code_listener.class%
        arguments: [@enuygun_com_dfp.collection, @enuygun_com_dfp.settings, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse}

    enuygun_com_dfp.twig.extension:
        class: %enuygun_com_dfp.twig.extension.class%
        arguments: [@enuygun_com_dfp.settings, @enuygun_com_dfp.collection]
        tags:
           - { name: twig.extension }