parameters:
    enuygun_dfp.control_code_listener.class: EnuygunCom\DfpBundle\EventListener\ControlCodeListener
    enuygun_dfp.collection.class: EnuygunCom\DfpBundle\Model\Collection
    enuygun_dfp.settings.class: EnuygunCom\DfpBundle\Model\Settings
    enuygun_dfp.twig.extension.class: EnuygunCom\DfpBundle\Twig\Extension\DfpExtension

    enuygun_dfp.publisher_id: ~
    enuygun_dfp.default_div_class: ~
    enuygun_dfp.targets: [ ]

services:
    enuygun_dfp.collection:
        class: %enuygun_dfp.collection.class%

    enuygun_dfp.settings:
        class: %enuygun_dfp.settings.class%
        arguments: [%enuygun_dfp.publisher_id%, %enuygun_dfp.default_div_class%, %enuygun_dfp.targets%, @kernel, @doctrine.dbal.default_connection, @memcached_client]

    enuygun_dfp.control_code_listener:
        class: %enuygun_dfp.control_code_listener.class%
        arguments: [@enuygun_dfp.collection, @enuygun_dfp.settings, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse}

    enuygun_dfp.twig.extension:
        class: %enuygun_dfp.twig.extension.class%
        arguments: [@enuygun_dfp.settings, @enuygun_dfp.collection]
        tags:
           - { name: twig.extension }